global:
  resolve_timeout: 5m

route:
  receiver: webhook
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: webhook
    webhook_configs:
      - url: http://host.docker.internal:18080/alertmanager
